### PR TITLE
Upgrade to python 3

### PR DESCRIPTION
**Pull request by omar-virta-health**
Upgrade to be used with Python 3

### CODE REVIEW

**Comment by maudineormsby** [comment]
Hi,

Thanks for opening the PR. Travis doesn't support running tests on Sauce from PRs (although I notice they have an addon that should enable that), so that's why the build is failing. 

Is this the only change needed for Python3?

**Comment by omar-virta-health** [comment]
Hi @maudineormsby Yes, we've forked your repo and run the code with this changes on our Python 3 code base and it's working great. 

Thanks for answering so fast

**Comment by maudineormsby** [comment]
@omar-virta-health I am merging this to get Python 3 into the released version. Let me know if there are any features you would like me to add; I have some time to work on this further.

**Comment by omar-virta-health** [comment]
Thanks @maudineormsby. 
At this time everything is working fine for us. 
I'll let you know if something comes up.

**Pull request merged**
